### ISSUE TITLE
Conda environment installing incorrectely

### ISSUE THREAD

**Issue by JaakkoAhola** [Snowflake-Labs/sfguide-getting-started-snowpark-python#3]
I installed the conda environment with the command `conda env create -f jupyter_env.yml`.
When running the following python command:
`from snowflake.snowpark import version`
python throws an error:

> UserWarning: You have an incompatible version of 'pyarrow' installed (8.0.0), please install a version that adheres to: 'pyarrow<6.1.0,>=6.0.0; extra == "pandas"'
>   warn_incompatible_dep(

**Comment by sfc-gh-cbaechtold** [comment]
Hi @JaakkoAhola -

Can you please confirm that you have activated the conda environment? `conda activate getting_started_with_snowpark_python` ?

Once you have done this, can you also confirm the version of the Snowflake Python connector that has been installed into the virtual env?
```python
>>> import snowflake.connector as snc
>>> snc.__version__
'2.7.11`
```

If you aren't seeing this version of the connector, please delete the conda env using `conda env remove -n getting_started_with_snowpark_python`, re-create it, and then try again and let me know what you find.

Thanks,
Caleb

**Comment by sfc-gh-cbaechtold** [comment]
I just re-created a fresh conda environment using the instructions and had no issues, so want to make sure that we are working off the same environment specs.

**Comment by JaakkoAhola** [comment]
The conda environment is activated and I have confirmed that I use correct python (python path double checked).
I have re-created a fresh conda environment with the same outcome (several times).
The output of `conda --version` is "conda 4.14.0".

Just to be clear, the [jupyter_env.yml ](https://github.com/Snowflake-Labs/sfguide-getting-started-snowpark-python/blob/main/customer-churn-prediction/jupyter_env.yml) does not specify the version of pyarrow.

I even made a fresh anaconda installation (conda version 4.12.0) but ended up with the same result.

All these efforts throw the same following error:
```
>>> import snowflake.connector as snc
/home/${USER}/.local/lib/python3.8/site-packages/snowflake/connector/options.py:96: UserWarning: You have an incompatible version of 'pyarrow' installed (8.0.0), please install a version that adheres to: 'pyarrow<6.1.0,>=6.0.0; extra == "pandas"'
  warn_incompatible_dep(
```

**Comment by sfc-gh-cbaechtold** [comment]
@JaakkoAhola can you please add `pyarrow==6.0.1` to the `jupyter_env.yml` **_before_** the `snowflake-snowpark-python` line? e.g.:
```yaml
- pyarrow==6.0.1
- snowflake-snowpark-python[pandas]==0.7.0
```
and then recreate the environment? I'm not seeing the same issue when I create new envs, but let's try forcing the pyarrow version and see if that works.

**Comment by sfc-gh-cbaechtold** [comment]
Actually sorry that will not work, `6.0.1` does not appear to be in the Snowflake/Anaconda channel.. going to continue trying some things on my side, will report back

**Comment by sfc-gh-cbaechtold** [comment]
@JaakkoAhola can you please run `conda info` and `conda list` from inside the activated environment and provide the output?

**Comment by JaakkoAhola** [comment]
```
$ conda info

     active environment : getting_started_snowpark_python
    active env location : /home/${USER}/anaconda3/envs/getting_started_snowpark_python
            shell level : 3
       user config file : /home/${USER}/.condarc
 populated config files : 
          conda version : 4.14.0
    conda-build version : 3.21.5
         python version : 3.9.7.final.0
       virtual packages : __linux=5.15.0=0
                          __glibc=2.35=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/${USER}/anaconda3  (writable)
      conda av data dir : /home/${USER}/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/${USER}/anaconda3/pkgs
                          /home/${USER}/.conda/pkgs
       envs directories : /home/${USER}/anaconda3/envs
                          /home/${USER}/.conda/envs
               platform : linux-64
             user-agent : conda/4.14.0 requests/2.26.0 CPython/3.9.7 Linux/5.15.0-46-generic ubuntu/22.04.1 glibc/2.35
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
```
$ conda list
# packages in environment at /home/${USER}/anaconda3/envs/getting_started_snowpark_python:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    https://repo.anaconda.com/pkgs/snowflake
_openmp_mutex             5.1                       1_gnu    https://repo.anaconda.com/pkgs/snowflake
abseil-cpp                20211102.0           hd4dd3e8_0    https://repo.anaconda.com/pkgs/snowflake
anyio                     3.5.0            py38h06a4308_0    https://repo.anaconda.com/pkgs/snowflake
argon2-cffi               21.3.0             pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/snowflake
argon2-cffi-bindings      21.2.0           py38h7f8727e_0    https://repo.anaconda.com/pkgs/snowflake
arrow-cpp                 8.0.0            py38h60b952e_0    https://repo.anaconda.com/pkgs/snowflake
asn1crypto                1.5.1            py38h06a4308_0    https://repo.anaconda.com/pkgs/snowflake
asttokens                 2.0.5              pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/snowflake
attrs                     21.4.0             pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/snowflake
aws-c-common              0.4.57               he6710b0_1    https://repo.anaconda.com/pkgs/snowflake
aws-c-event-stream        0.1.6                h2531618_5    https://repo.anaconda.com/pkgs/snowflake
aws-checksums             0.1.9                he6710b0_0    https://repo.anaconda.com/pkgs/snowflake
aws-sdk-cpp               1.8.185              hce553d0_0    https://repo.anaconda.com/pkgs/snowflake
babel                     2.9.1              pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/snowflake
backcall                  0.2.0              pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/snowflake
beautifulsoup4            4.11.1           py38h06a4308_0    https://repo.anaconda.com/pkgs/snowflake
blas                      1.0                         mkl    https://repo.anaconda.com/pkgs/snowflake
bleach                    4.1.0              pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/snowflake
boost-cpp                 1.73.0              h7f8727e_12    https://repo.anaconda.com/pkgs/snowflake
bottleneck                1.3.5            py38h7deecbd_0    https://repo.anaconda.com/pkgs/snowflake
brotli                    1.0.9                h5eee18b_7    https://repo.anaconda.com/pkgs/snowflake
brotli-bin                1.0.9                h5eee18b_7    https://repo.anaconda.com/pkgs/snowflake
brotlipy                  0.7.0           py38h27cfd23_1003    https://repo.anaconda.com/pkgs/snowflake
bzip2                     1.0.8                h7b6447c_0    https://repo.anaconda.com/pkgs/snowflake
c-ares                    1.18.1               h7f8727e_0    https://repo.anaconda.com/pkgs/snowflake
ca-certificates           2022.07.19           h06a4308_0    https://repo.anaconda.com/pkgs/snowflake
certifi                   2022.6.15        py38h06a4308_0    https://repo.anaconda.com/pkgs/snowflake
cffi                      1.15.1           py38h74dc2b5_0    https://repo.anaconda.com/pkgs/snowflake
charset-normalizer        2.0.4              pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/snowflake
cloudpickle               2.0.0              pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/snowflake
cryptography              36.0.0           py38h9ce1e76_0    https://repo.anaconda.com/pkgs/snowflake
cycler                    0.11.0             pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/snowflake
dbus                      1.13.18              hb2f20db_0    https://repo.anaconda.com/pkgs/snowflake
debugpy                   1.5.1            py38h295c915_0    https://repo.anaconda.com/pkgs/snowflake
decorator                 5.1.1              pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/snowflake
defusedxml                0.7.1              pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/snowflake
entrypoints               0.4              py38h06a4308_0    https://repo.anaconda.com/pkgs/snowflake
executing                 0.8.3              pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/snowflake
expat                     2.4.4                h295c915_0    https://repo.anaconda.com/pkgs/snowflake
fontconfig                2.13.1               h6c09931_0    https://repo.anaconda.com/pkgs/snowflake
fonttools                 4.25.0             pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/snowflake
freetype                  2.11.0               h70c0345_0    https://repo.anaconda.com/pkgs/snowflake
gflags                    2.2.2                he6710b0_0    https://repo.anaconda.com/pkgs/snowflake
giflib                    5.2.1                h7b6447c_0    https://repo.anaconda.com/pkgs/snowflake
glib                      2.69.1               h4ff587b_1    https://repo.anaconda.com/pkgs/snowflake
glog                      0.5.0                h2531618_0    https://repo.anaconda.com/pkgs/snowflake
gmp                       6.2.1                h295c915_3    https://repo.anaconda.com/pkgs/snowflake
grpc-cpp                  1.46.1               h33aed49_0    https://repo.anaconda.com/pkgs/snowflake
gst-plugins-base          1.14.0               h8213a91_2    https://repo.anaconda.com/pkgs/snowflake
gstreamer                 1.14.0               h28cd5cc_2    https://repo.anaconda.com/pkgs/snowflake
icu                       58.2                 he6710b0_3    https://repo.anaconda.com/pkgs/snowflake
idna                      3.3                pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/snowflake
importlib_resources       5.2.0              pyhd3eb1b0_1    https://repo.anaconda.com/pkgs/snowflake
intel-openmp              2021.4.0          h06a4308_3561    https://repo.anaconda.com/pkgs/snowflake
ipykernel                 6.9.1            py38h06a4308_0    https://repo.anaconda.com/pkgs/snowflake
ipython                   8.4.0            py38h06a4308_0    https://repo.anaconda.com/pkgs/snowflake
ipython_genutils          0.2.0              pyhd3eb1b0_1    https://repo.anaconda.com/pkgs/snowflake
ipywidgets                7.6.5              pyhd3eb1b0_1    https://repo.anaconda.com/pkgs/snowflake
jedi                      0.18.1           py38h06a4308_1    https://repo.anaconda.com/pkgs/snowflake
jinja2                    3.0.3              pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/snowflake
joblib                    1.1.0              pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/snowflake
jpeg                      9e                   h7f8727e_0    https://repo.anaconda.com/pkgs/snowflake
json5                     0.9.6              pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/snowflake
jsonschema                4.4.0            py38h06a4308_0    https://repo.anaconda.com/pkgs/snowflake
jupyter                   1.0.0            py38h06a4308_8    https://repo.anaconda.com/pkgs/snowflake
jupyter_client            7.2.2            py38h06a4308_0    https://repo.anaconda.com/pkgs/snowflake
jupyter_console           6.4.3              pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/snowflake
jupyter_core              4.10.0           py38h06a4308_0    https://repo.anaconda.com/pkgs/snowflake
jupyter_server            1.18.1           py38h06a4308_0    https://repo.anaconda.com/pkgs/snowflake
jupyterlab                3.4.4            py38h06a4308_0    https://repo.anaconda.com/pkgs/snowflake
jupyterlab_pygments       0.1.2                      py_0    https://repo.anaconda.com/pkgs/snowflake
jupyterlab_server         2.12.0           py38h06a4308_0    https://repo.anaconda.com/pkgs/snowflake
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1    https://repo.anaconda.com/pkgs/snowflake
kiwisolver                1.4.2            py38h295c915_0    https://repo.anaconda.com/pkgs/snowflake
krb5                      1.19.2               hac12032_0    https://repo.anaconda.com/pkgs/snowflake
lcms2                     2.12                 h3be6417_0    https://repo.anaconda.com/pkgs/snowflake
ld_impl_linux-64          2.38                 h1181459_1    https://repo.anaconda.com/pkgs/snowflake
libboost                  1.73.0              h28710b8_12    https://repo.anaconda.com/pkgs/snowflake
libbrotlicommon           1.0.9                h5eee18b_7    https://repo.anaconda.com/pkgs/snowflake
libbrotlidec              1.0.9                h5eee18b_7    https://repo.anaconda.com/pkgs/snowflake
libbrotlienc              1.0.9                h5eee18b_7    https://repo.anaconda.com/pkgs/snowflake
libclang                  10.0.1          default_hb85057a_2    https://repo.anaconda.com/pkgs/snowflake
libcurl                   7.84.0               h91b91d3_0    https://repo.anaconda.com/pkgs/snowflake
libedit                   3.1.20210910         h7f8727e_0    https://repo.anaconda.com/pkgs/snowflake
libev                     4.33                 h7f8727e_1    https://repo.anaconda.com/pkgs/snowflake
libevent                  2.1.12               h8f2d780_0    https://repo.anaconda.com/pkgs/snowflake
libffi                    3.3                  he6710b0_2    https://repo.anaconda.com/pkgs/snowflake
libgcc-ng                 11.2.0               h1234567_1    https://repo.anaconda.com/pkgs/snowflake
libgfortran-ng            7.5.0               ha8ba4b0_17    https://repo.anaconda.com/pkgs/snowflake
libgfortran4              7.5.0               ha8ba4b0_17    https://repo.anaconda.com/pkgs/snowflake
libgomp                   11.2.0               h1234567_1    https://repo.anaconda.com/pkgs/snowflake
libllvm10                 10.0.1               hbcb73fb_5    https://repo.anaconda.com/pkgs/snowflake
libnghttp2                1.46.0               hce63b2e_0    https://repo.anaconda.com/pkgs/snowflake
libpng                    1.6.37               hbc83047_0    https://repo.anaconda.com/pkgs/snowflake
libpq                     12.9                 h16c4e8d_3    https://repo.anaconda.com/pkgs/snowflake
libprotobuf               3.20.1               h4ff587b_0    https://repo.anaconda.com/pkgs/snowflake
libsodium                 1.0.18               h7b6447c_0    https://repo.anaconda.com/pkgs/snowflake
libssh2                   1.10.0               h8f2d780_0    https://repo.anaconda.com/pkgs/snowflake
libstdcxx-ng              11.2.0               h1234567_1    https://repo.anaconda.com/pkgs/snowflake
libthrift                 0.15.0               hcc01f38_0    https://repo.anaconda.com/pkgs/snowflake
libtiff                   4.2.0                h2818925_1    https://repo.anaconda.com/pkgs/snowflake
libuuid                   1.0.3                h7f8727e_2    https://repo.anaconda.com/pkgs/snowflake
libwebp                   1.2.2                h55f646e_0    https://repo.anaconda.com/pkgs/snowflake
libwebp-base              1.2.2                h7f8727e_0    https://repo.anaconda.com/pkgs/snowflake
libxcb                    1.15                 h7f8727e_0    https://repo.anaconda.com/pkgs/snowflake
libxkbcommon              1.0.1                hfa300c1_0    https://repo.anaconda.com/pkgs/snowflake
libxml2                   2.9.14               h74e7548_0    https://repo.anaconda.com/pkgs/snowflake
libxslt                   1.1.35               h4e12654_0    https://repo.anaconda.com/pkgs/snowflake
lz4-c                     1.9.3                h295c915_1    https://repo.anaconda.com/pkgs/snowflake
markupsafe                2.1.1            py38h7f8727e_0    https://repo.anaconda.com/pkgs/snowflake
matplotlib                3.5.2            py38h06a4308_0  
matplotlib-base           3.5.2            py38hf590b9c_0  
matplotlib-inline         0.1.2              pyhd3eb1b0_2    https://repo.anaconda.com/pkgs/snowflake
mistune                   0.8.4           py38h7b6447c_1000    https://repo.anaconda.com/pkgs/snowflake
mkl                       2021.4.0           h06a4308_640    https://repo.anaconda.com/pkgs/snowflake
mkl-service               2.4.0            py38h7f8727e_0    https://repo.anaconda.com/pkgs/snowflake
mkl_fft                   1.3.1            py38hd3c417c_0    https://repo.anaconda.com/pkgs/snowflake
mkl_random                1.2.2            py38h51133e4_0    https://repo.anaconda.com/pkgs/snowflake
munkres                   1.1.4                      py_0    https://repo.anaconda.com/pkgs/snowflake
nbclassic                 0.3.5              pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/snowflake
nbclient                  0.5.13           py38h06a4308_0    https://repo.anaconda.com/pkgs/snowflake
nbconvert                 6.4.4            py38h06a4308_0    https://repo.anaconda.com/pkgs/snowflake
nbformat                  5.3.0            py38h06a4308_0    https://repo.anaconda.com/pkgs/snowflake
ncurses                   6.3                  h5eee18b_3    https://repo.anaconda.com/pkgs/snowflake
nest-asyncio              1.5.5            py38h06a4308_0    https://repo.anaconda.com/pkgs/snowflake
notebook                  6.4.12           py38h06a4308_0    https://repo.anaconda.com/pkgs/snowflake
nspr                      4.33                 h295c915_0    https://repo.anaconda.com/pkgs/snowflake
nss                       3.74                 h0370c37_0    https://repo.anaconda.com/pkgs/snowflake
numexpr                   2.8.3            py38h807cd23_0    https://repo.anaconda.com/pkgs/snowflake
numpy                     1.23.1           py38h6c91a56_0    https://repo.anaconda.com/pkgs/snowflake
numpy-base                1.23.1           py38ha15fc14_0    https://repo.anaconda.com/pkgs/snowflake
openssl                   1.1.1q               h7f8727e_0    https://repo.anaconda.com/pkgs/snowflake
orc                       1.7.4                h07ed6aa_0    https://repo.anaconda.com/pkgs/snowflake
oscrypto                  1.2.1              pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/snowflake
packaging                 21.3               pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/snowflake
pandas                    1.3.5            py38h8c16a72_0    https://repo.anaconda.com/pkgs/snowflake
pandocfilters             1.5.0              pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/snowflake
parso                     0.8.3              pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/snowflake
pcre                      8.45                 h295c915_0    https://repo.anaconda.com/pkgs/snowflake
pexpect                   4.8.0              pyhd3eb1b0_3    https://repo.anaconda.com/pkgs/snowflake
pickleshare               0.7.5           pyhd3eb1b0_1003    https://repo.anaconda.com/pkgs/snowflake
pillow                    9.2.0            py38hace64e9_1    https://repo.anaconda.com/pkgs/snowflake
pip                       22.1.2           py38h06a4308_0    https://repo.anaconda.com/pkgs/snowflake
ply                       3.11                     py38_0    https://repo.anaconda.com/pkgs/snowflake
prometheus_client         0.14.1           py38h06a4308_0    https://repo.anaconda.com/pkgs/snowflake
prompt-toolkit            3.0.20             pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/snowflake
prompt_toolkit            3.0.20               hd3eb1b0_0    https://repo.anaconda.com/pkgs/snowflake
ptyprocess                0.7.0              pyhd3eb1b0_2    https://repo.anaconda.com/pkgs/snowflake
pure_eval                 0.2.2              pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/snowflake
pyarrow                   8.0.0            py38h992f0b0_0    https://repo.anaconda.com/pkgs/snowflake
pycparser                 2.21               pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/snowflake
pycryptodomex             3.10.1           py38h27cfd23_1    https://repo.anaconda.com/pkgs/snowflake
pygments                  2.11.2             pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/snowflake
pyjwt                     2.4.0            py38h06a4308_0    https://repo.anaconda.com/pkgs/snowflake
pyopenssl                 22.0.0             pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/snowflake
pyparsing                 3.0.4              pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/snowflake
pyqt                      5.15.7           py38h6a678d5_1    https://repo.anaconda.com/pkgs/snowflake
pyqt5-sip                 12.11.0          py38h6a678d5_1    https://repo.anaconda.com/pkgs/snowflake
pyrsistent                0.18.0           py38heee7806_0    https://repo.anaconda.com/pkgs/snowflake
pysocks                   1.7.1            py38h06a4308_0    https://repo.anaconda.com/pkgs/snowflake
python                    3.8.13               h12debd9_0    https://repo.anaconda.com/pkgs/snowflake
python-dateutil           2.8.2              pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/snowflake
python-fastjsonschema     2.15.1             pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/snowflake
pytz                      2022.1           py38h06a4308_0    https://repo.anaconda.com/pkgs/snowflake
pyzmq                     23.2.0           py38h6a678d5_0    https://repo.anaconda.com/pkgs/snowflake
qt-main                   5.15.2               h327a75a_6    https://repo.anaconda.com/pkgs/snowflake
qt-webengine              5.15.9               hd2b0992_4    https://repo.anaconda.com/pkgs/snowflake
qtconsole                 5.3.1            py38h06a4308_1    https://repo.anaconda.com/pkgs/snowflake
qtpy                      2.0.1              pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/snowflake
qtwebkit                  5.212                h4eab89a_4    https://repo.anaconda.com/pkgs/snowflake
re2                       2022.04.01           h295c915_0    https://repo.anaconda.com/pkgs/snowflake
readline                  8.1.2                h7f8727e_1    https://repo.anaconda.com/pkgs/snowflake
requests                  2.28.1           py38h06a4308_0    https://repo.anaconda.com/pkgs/snowflake
scikit-learn              1.0.2            py38h51133e4_1    https://repo.anaconda.com/pkgs/snowflake
scipy                     1.7.1            py38h292c36d_2    https://repo.anaconda.com/pkgs/snowflake
seaborn                   0.11.2             pyhd3eb1b0_0  
send2trash                1.8.0              pyhd3eb1b0_1    https://repo.anaconda.com/pkgs/snowflake
setuptools                61.2.0           py38h06a4308_0    https://repo.anaconda.com/pkgs/snowflake
sip                       6.6.2            py38h6a678d5_0    https://repo.anaconda.com/pkgs/snowflake
six                       1.16.0             pyhd3eb1b0_1    https://repo.anaconda.com/pkgs/snowflake
snappy                    1.1.9                h295c915_0    https://repo.anaconda.com/pkgs/snowflake
sniffio                   1.2.0            py38h06a4308_1    https://repo.anaconda.com/pkgs/snowflake
snowflake-connector-python 2.7.11           py38h417a72b_0    https://repo.anaconda.com/pkgs/snowflake
snowflake-snowpark-python 0.7.0            py38h06a4308_0    https://repo.anaconda.com/pkgs/snowflake
soupsieve                 2.3.1              pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/snowflake
sqlite                    3.39.0               h5082296_0    https://repo.anaconda.com/pkgs/snowflake
stack_data                0.2.0              pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/snowflake
terminado                 0.13.1           py38h06a4308_0    https://repo.anaconda.com/pkgs/snowflake
testpath                  0.6.0            py38h06a4308_0    https://repo.anaconda.com/pkgs/snowflake
threadpoolctl             2.2.0              pyh0d69192_0    https://repo.anaconda.com/pkgs/snowflake
tk                        8.6.12               h1ccaba5_0    https://repo.anaconda.com/pkgs/snowflake
toml                      0.10.2             pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/snowflake
tornado                   6.1              py38h27cfd23_0    https://repo.anaconda.com/pkgs/snowflake
traitlets                 5.1.1              pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/snowflake
typing-extensions         4.3.0            py38h06a4308_0    https://repo.anaconda.com/pkgs/snowflake
typing_extensions         4.3.0            py38h06a4308_0    https://repo.anaconda.com/pkgs/snowflake
urllib3                   1.26.11          py38h06a4308_0    https://repo.anaconda.com/pkgs/snowflake
utf8proc                  2.6.1                h27cfd23_0    https://repo.anaconda.com/pkgs/snowflake
wcwidth                   0.2.5              pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/snowflake
webencodings              0.5.1                    py38_1    https://repo.anaconda.com/pkgs/snowflake
websocket-client          0.58.0           py38h06a4308_4    https://repo.anaconda.com/pkgs/snowflake
wheel                     0.37.1             pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/snowflake
widgetsnbextension        3.5.2            py38h06a4308_0    https://repo.anaconda.com/pkgs/snowflake
xz                        5.2.5                h7f8727e_1    https://repo.anaconda.com/pkgs/snowflake
zeromq                    4.3.4                h2531618_0    https://repo.anaconda.com/pkgs/snowflake
zipp                      3.8.0            py38h06a4308_0    https://repo.anaconda.com/pkgs/snowflake
zlib                      1.2.12               h7f8727e_2    https://repo.anaconda.com/pkgs/snowflake
zstd                      1.5.2                ha4553b6_0    https://repo.anaconda.com/pkgs/snowflake
```

**Comment by JaakkoAhola** [comment]
In my previous comment I said:

> All these efforts throw the same following error:
> 
> ```
> >>> import snowflake.connector as snc
> /home/${USER}/.local/lib/python3.8/site-packages/snowflake/connector/options.py:96: UserWarning: You have an incompatible version of 'pyarrow' installed (8.0.0), please install a version that adheres to: 'pyarrow<6.1.0,>=6.0.0; extra == "pandas"'
>   warn_incompatible_dep(
> ```

Now I am wondering why on earth the path starts with  `/home/${USER}/.local` maybe there's the problem.

**Comment by sfc-gh-cbaechtold** [comment]
Thank you, @JaakkoAhola . Your package versions all look correct from the `conda list` command, and the connector `2.7.11` has `pyarrow==8.0.0` support so I'm a little unsure why you're seeing that user warning.

It appears that it may be related to somehow loading the connector from outside of the conda env, based on your most recent comment. I would verify that your Python kernel is from the conda env, as you do have all correct package versions installed into the env, and your `list` command mirrors my own working env exactly (without any sort of user warning)

**Comment by JaakkoAhola** [comment]
To make sure I even used the command
`/home/${USER}/anaconda3/envs/getting_started_snowpark_python/bin/python -m ipykernel install --user --name=getting_started_snowpark_python` with the explicit python to create the kernel but ended up with the same result.

Do you @sfc-gh-cbaechtold  have an idea why or from what python path it reads the `/home/${USER}/.local`?

**Comment by mcg1969** [comment]
Michael from Anaconda here. @sfc-gh-cbaechtold alerted me to this, and we both have had difficulty reproducing the issue. And in fact your environment looks right.

But I think you're on to something. Can you try this _outside of Jupyter_ for a moment to try and reproduce the error? That is, launch a terminal, activate the environment, fire up python, and run the import command there?

I think the `/home/.../.local` thing is a Jupyter construct and maybe that's getting in the way somehow.

Also, do you have PYTHONPATH set to anything? Do you use other kinds of virtual Python environments besides conda?

**Comment by mcg1969** [comment]
Another possibility is that a different Python install created that directory and it is getting priority when it shouldn't. It might need to be removed.

**Comment by JaakkoAhola** [comment]
The error occurs also outside of jupyter by just running python from the terminal.
I removed all the conda environments (one env had a snowflake connector installed with pip) but it did not help. I do not have any other virtual envs.

PYTHONPATH is not pointing to anything. I temporarily removed all the .local references from PATH to no avail.

Spur of the moment I removed with 
`rm -rf /home/${USER}/.local/lib/python3.8/site-packages/snowflake /home/${USER}/.local/lib/python3.8/site-packages/snowflake*` and made a fresh conda env.

The notebook ran well until
```
session = Session.builder.configs(snowflake_conn_prop).create()
```
threw error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/${USER}/anaconda3/envs/snowpark_tutorial/lib/python3.8/site-packages/snowflake/snowpark/session.py", line 204, in create
    return self._create_internal(conn=None)
  File "/home/${USER}/anaconda3/envs/snowpark_tutorial/lib/python3.8/site-packages/snowflake/snowpark/session.py", line 210, in _create_internal
    ServerConnection({}, conn) if conn else ServerConnection(self._options)
  File "/home/${USER}/anaconda3/envs/snowpark_tutorial/lib/python3.8/site-packages/snowflake/snowpark/_internal/server_connection.py", line 136, in __init__
    self._conn = conn if conn else connect(**self._lower_case_parameters)
  File "/home/${USER}/anaconda3/envs/snowpark_tutorial/lib/python3.8/site-packages/snowflake/connector/__init__.py", line 51, in Connect
    return SnowflakeConnection(**kwargs)
  File "/home/${USER}/anaconda3/envs/snowpark_tutorial/lib/python3.8/site-packages/snowflake/connector/connection.py", line 292, in __init__
    self.connect(**kwargs)
  File "/home/${USER}/anaconda3/envs/snowpark_tutorial/lib/python3.8/site-packages/snowflake/connector/connection.py", line 542, in connect
    self.__open_connection()
  File "/home/${USER}/anaconda3/envs/snowpark_tutorial/lib/python3.8/site-packages/snowflake/connector/connection.py", line 781, in __open_connection
    self._authenticate(auth_instance)
  File "/home/${USER}/anaconda3/envs/snowpark_tutorial/lib/python3.8/site-packages/snowflake/connector/connection.py", line 1044, in _authenticate
    self.__authenticate(self.__preprocess_auth_instance(auth_instance))
  File "/home/${USER}/anaconda3/envs/snowpark_tutorial/lib/python3.8/site-packages/snowflake/connector/connection.py", line 1064, in __authenticate
    auth.authenticate(
  File "/home/${USER}/anaconda3/envs/snowpark_tutorial/lib/python3.8/site-packages/snowflake/connector/auth.py", line 257, in authenticate
    ret = self._rest._post_request(
  File "/home/${USER}/anaconda3/envs/snowpark_tutorial/lib/python3.8/site-packages/snowflake/connector/network.py", line 704, in _post_request
    ret = self.fetch(
  File "/home/${USER}/anaconda3/envs/snowpark_tutorial/lib/python3.8/site-packages/snowflake/connector/network.py", line 794, in fetch
    ret = self._request_exec_wrapper(
  File "/home/${USER}/anaconda3/envs/snowpark_tutorial/lib/python3.8/site-packages/snowflake/connector/network.py", line 917, in _request_exec_wrapper
    raise e
  File "/home/${USER}/anaconda3/envs/snowpark_tutorial/lib/python3.8/site-packages/snowflake/connector/network.py", line 837, in _request_exec_wrapper
    return_object = self._request_exec(
  File "/home/${USER}/anaconda3/envs/snowpark_tutorial/lib/python3.8/site-packages/snowflake/connector/network.py", line 1116, in _request_exec
    raise err
  File "/home/${USER}/anaconda3/envs/snowpark_tutorial/lib/python3.8/site-packages/snowflake/connector/network.py", line 1018, in _request_exec
    raw_ret = session.request(
  File "/home/${USER}/anaconda3/envs/snowpark_tutorial/lib/python3.8/site-packages/snowflake/connector/vendored/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/${USER}/anaconda3/envs/snowpark_tutorial/lib/python3.8/site-packages/snowflake/connector/vendored/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/${USER}/anaconda3/envs/snowpark_tutorial/lib/python3.8/site-packages/snowflake/connector/vendored/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/${USER}/anaconda3/envs/snowpark_tutorial/lib/python3.8/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/${USER}/anaconda3/envs/snowpark_tutorial/lib/python3.8/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/${USER}/anaconda3/envs/snowpark_tutorial/lib/python3.8/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/${USER}/anaconda3/envs/snowpark_tutorial/lib/python3.8/site-packages/snowflake/connector/vendored/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/home/${USER}/anaconda3/envs/snowpark_tutorial/lib/python3.8/site-packages/snowflake/connector/ssl_wrap_socket.py", line 78, in ssl_wrap_socket_with_ocsp
    from .ocsp_asn1crypto import SnowflakeOCSPAsn1Crypto as SFOCSP
  File "/home/${USER}/anaconda3/envs/snowpark_tutorial/lib/python3.8/site-packages/snowflake/connector/ocsp_asn1crypto.py", line 47, in <module>
    from snowflake.connector.ocsp_snowflake import SnowflakeOCSP
  File "/home/${USER}/anaconda3/envs/snowpark_tutorial/lib/python3.8/site-packages/snowflake/connector/ocsp_snowflake.py", line 71, in <module>
    from .cache import SFDictCache
  File "/home/${USER}/anaconda3/envs/snowpark_tutorial/lib/python3.8/site-packages/snowflake/connector/cache.py", line 12, in <module>
    from typing_extensions import NamedTuple, Self
ImportError: cannot import name 'NamedTuple' from 'typing_extensions' (/home/${USER}/.local/lib/python3.8/site-packages/typing_extensions.py)
```

I guess I went from bad to worse.
Any ideas how I could start from a clean python slate without messing my OS?

**Comment by JaakkoAhola** [comment]
I uninstalled all my pip installations with `pip freeze | xargs pip uninstall -y`, I removed `~/.local/lib/python3.8/site-packages/` and my anaconda folder. Then I re-installed anaconda and the conda environment given in this repo. Now it seems to be working.
